In [1]:
from keras.datasets import imdb
from keras.preprocessing import sequence
from keras import Sequential
from keras.layers import Embedding, LSTM, Dense, Dropout

/Users/spacslug/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
vocabulary_size = 5000

(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words = vocabulary_size)

In [3]:
max_words = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_words)
X_test = sequence.pad_sequences(X_test, maxlen=max_words)

In [4]:
embedding_size=32
model=Sequential()
model.add(Embedding(vocabulary_size, embedding_size, input_length=max_words))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))

print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 500, 32)           160000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               53200     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 213,301
Trainable params: 213,301
Non-trainable params: 0
_________________________________________________________________
None


In [5]:
model.compile(loss='binary_crossentropy', 
             optimizer='adam', 
             metrics=['accuracy'])

In [6]:
batch_size = 64

num_epochs = 3

X_valid, y_valid = X_train[:batch_size], y_train[:batch_size]
X_train2, y_train2 = X_train[batch_size:], y_train[batch_size:]

model.fit(X_train2, y_train2, validation_data=(X_valid, y_valid), batch_size=batch_size, epochs=num_epochs)

Train on 24936 samples, validate on 64 samples
Epoch 1/3
24936/24936 [==============================] - 281s 11ms/step - loss: 0.4275 - acc: 0.7968 - val_loss: 0.2204 - val_acc: 0.9531
Epoch 2/3
24936/24936 [==============================] - 276s 11ms/step - loss: 0.2890 - acc: 0.8848 - val_loss: 0.2556 - val_acc: 0.8906
Epoch 3/3
24936/24936 [==============================] - 325s 13ms/step - loss: 0.2495 - acc: 0.9036 - val_loss: 0.2517 - val_acc: 0.8750


In [161]:
x = open("/Users/spacslug/Desktop/review.txt",'r').read()

In [162]:
from nltk import sent_tokenize
from nltk.tokenize import word_tokenize

sentences = sent_tokenize(x)
sentences
words = [word for word in sentences if word.isalpha()]
words

[]

In [163]:
tokens = word_tokenize(x)
words = [word for word in tokens if word.isalpha()]
words

['Lagaan',
 'is',
 'an',
 'enormously',
 'entertaining',
 'movie',
 'like',
 'nothing',
 'we',
 'ever',
 'seen',
 'before',
 'and',
 'yet',
 'completely',
 'familiar',
 'Set',
 'in',
 'India',
 'in',
 'it',
 'combines',
 'sports',
 'with',
 'political',
 'intrigue',
 'romance',
 'with',
 'evil',
 'scheming',
 'musical',
 'numbers',
 'with',
 'low',
 'comedy',
 'and',
 'high',
 'drama',
 'and',
 'is',
 'therefore',
 'soundly',
 'in',
 'the',
 'tradition',
 'of',
 'the',
 'entertainments',
 'produced',
 'by',
 'the',
 'Bombay',
 'film',
 'industry',
 'Bollywood',
 'which',
 'is',
 'the',
 'world',
 'largest',
 'I',
 'have',
 'seen',
 'only',
 'five',
 'or',
 'six',
 'Bollywood',
 'movies',
 'one',
 'of',
 'them',
 'in',
 'Hyderabad',
 'India',
 'in',
 'where',
 'I',
 'climbed',
 'to',
 'the',
 'highest',
 'balcony',
 'and',
 'shivered',
 'in',
 'arctic',
 'air',
 'conditioning',
 'while',
 'watching',
 'a',
 'movie',
 'that',
 'was',
 'well',
 'over',
 'three',
 'hours',
 'long',
 'and',

In [164]:
word2id = imdb.get_word_index()

In [165]:
lst = []

In [166]:
for i in x.split():
    if i in word2id.keys():
        lst.append(word2id[i])

In [167]:
lst

[6,
 32,
 8146,
 438,
 37,
 161,
 1999,
 123,
 107,
 2,
 243,
 337,
 8,
 8,
 9,
 6548,
 2252,
 16,
 990,
 880,
 16,
 442,
 618,
 1393,
 16,
 361,
 209,
 2,
 309,
 2,
 6,
 1614,
 47541,
 8,
 1,
 2952,
 4,
 1,
 21587,
 1052,
 31,
 1,
 19,
 60,
 6,
 1,
 3443,
 25,
 107,
 61,
 674,
 39,
 1443,
 28,
 4,
 95,
 8,
 8,
 118,
 16479,
 5,
 1,
 4079,
 9907,
 2,
 69609,
 8,
 12429,
 942,
 26704,
 134,
 146,
 3,
 17,
 12,
 13,
 70,
 117,
 286,
 631,
 193,
 2,
 1923,
 139,
 15,
 88,
 1217,
 1248,
 4,
 88,
 99,
 6,
 65,
 7768,
 13760,
 5,
 986,
 80,
 610,
 2,
 834,
 30,
 1,
 3635,
 1,
 19,
 216,
 13,
 41,
 3,
 880,
 197,
 3,
 1023,
 427,
 2,
 3,
 335,
 622,
 3457,
 119,
 21,
 3618,
 38,
 36,
 4034,
 3973,
 1942,
 56,
 884,
 6,
 298,
 5,
 27,
 1,
 88,
 3266,
 2,
 1109,
 19,
 123,
 2,
 44,
 74,
 3,
 566,
 29,
 117,
 1,
 34,
 6,
 28,
 4,
 1,
 347,
 9,
 13,
 90,
 16,
 32,
 741,
 5,
 9466,
 97,
 986,
 43,
 4,
 1,
 6788,
 2,
 2739,
 92,
 135,
 21,
 3,
 17,
 15,
 44,
 4099,
 8,
 3580,
 91,
 9,
 1196,
 32,
 

In [168]:
import numpy as np

In [169]:
ndar = np.array([lst])
ndar

array([[    6,    32,  8146,   438,    37,   161,  1999,   123,   107,
            2,   243,   337,     8,     8,     9,  6548,  2252,    16,
          990,   880,    16,   442,   618,  1393,    16,   361,   209,
            2,   309,     2,     6,  1614, 47541,     8,     1,  2952,
            4,     1, 21587,  1052,    31,     1,    19,    60,     6,
            1,  3443,    25,   107,    61,   674,    39,  1443,    28,
            4,    95,     8,     8,   118, 16479,     5,     1,  4079,
         9907,     2, 69609,     8, 12429,   942, 26704,   134,   146,
            3,    17,    12,    13,    70,   117,   286,   631,   193,
            2,  1923,   139,    15,    88,  1217,  1248,     4,    88,
           99,     6,    65,  7768, 13760,     5,   986,    80,   610,
            2,   834,    30,     1,  3635,     1,    19,   216,    13,
           41,     3,   880,   197,     3,  1023,   427,     2,     3,
          335,   622,  3457,   119,    21,  3618,    38,    36,  4034,
      

In [170]:
word_test = sequence.pad_sequences(ndar, maxlen=max_words)

In [171]:
#word2id.keys()[word2id.values().index(6200)]

In [172]:
word_test[word_test>5000] = 0

In [173]:
word_test

array([[ 237,  117,    1,   60,    6,    1,    0,    0,    1,    0,  212,
         987,    5,   65,    2,   26,    5,    1,    6,    3,   55,    4,
           0,    2,    2,    1,    0,  563,    3, 2118,  790,   24,   34,
           0,    2,  656,   24,  812, 1702,    6, 2189,   31,    2, 2248,
          42,    3,  497,   12,   67,  112,   27,    0,   31,  557,    9,
           6,   73,   37,   32, 2210,    2,   12,   97,    0,   30,  163,
           3,    2,    3, 2056,  765,   77,  294,    3,    0,    1,   47,
          77,   27,   54,    0,   15,  286,    1,    0,   77,   27,    0,
         101,    6,  234,    3,    0,    0,   59, 2327,   18,   26,  754,
          43,   12,  234,   33,  563,  987,    1, 2025,   33,   25,  161,
           5,    0,    2,  514,    5, 4309,    3,  716,    1,  442,    0,
        2248,   38,    0,  852,    6,    2, 4546,    0,   43,    5,    1,
        2056,    5, 1751,    0,   20,    0,    5,    0,    3,  716,  252,
          34,   44, 2414,  234, 1545, 

In [174]:
model.predict(word_test)

array([[0.62514883]], dtype=float32)